In [1]:
#multi dimensional indexing in numpy
# Axes in a 2D Array
import numpy as np
 
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
 
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
np.sum(arr, axis = 0) # Sum along rows (down each column)


array([12, 15, 18])

In [5]:
np.sum(arr, axis = 1) # Sum along columns (across each row)

array([ 6, 15, 24])

In [8]:
print(arr[1, 2]) # Row index 1, Column index 2 → Output: 6

6


In [9]:
print(arr[0:2, 1:3]) # Extracts first 2 rows and last 2 columns

[[2 3]
 [5 6]]


In [10]:
#For 3D arrays, the first index refers to the "depth" (sheets of data)

arr3D = np.array([[[1, 2, 3], [4, 5, 6]],   
                  [[7, 8, 9], [10, 11, 12]]])
print(arr3D)    


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
print(arr3D.shape) # Output of arr3D.shape is → (depth, rows, columns)

(2, 2, 3)


In [13]:
print(arr3D[0,1,2]) # First depth, second row, third column

6


In [14]:
print(arr3D[:, 0, :]) #all depth,first row, all columns

[[1 2 3]
 [7 8 9]]


In [15]:
# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
first_column = arr[:, 0]
print(first_column)

[1 4 7]


In [18]:
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)


[[1 0 3]
 [4 0 6]
 [7 0 9]]
