In [3]:
#1 find the memory size of a NumPy array with 1 million elements.

import numpy as np 
import time
import sys

In [22]:
list1 = list(range(1000000))
np1 = np.array(list1)
a = np1.nbytes
print(f"numpy takes {a} bytes") 

numpy takes 8000000 bytes


In [6]:
#2 compare the time taken to multiply two Python lists vs. two NumPy arrays.
#a python list:

list1 = list(range(100000))
list2 = list(range(100000))
start = time.time()
result = [x*y for x,y in zip(list1,list2)]
end = time.time()
print("time taken by this operation to run sucessfully is", end - start)

time taken by this operation to run sucessfully is 0.013371944427490234


In [7]:
#b. numpy arrays:

arr1 = np.array(list1)
arr2 = np.array(list2)
start =  time.time()
result = arr1*arr2
end = time.time()
print("time taken by this operation to run sucessfully is", end - start)

time taken by this operation to run sucessfully is 0.003021717071533203


In [8]:
0.01337/0.00302

4.427152317880794

In [12]:
#3. Create a 3×3 array filled with random numbers and print its shape.

x = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(x.shape)

(1, 3, 3)


In [13]:
print(x)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [18]:
#4. convert an array of floats [1.1, 2.2, 3.3] into integers.
    
l = [1.1, 2.2, 3.3]
arr = np.array(l)
l_int = arr.astype(np.int32)
print(l_int)

[1 2 3]


In [31]:
#5. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6]

list = [1, 2, 3, 4, 5, 6] 
arr = np.array(list)
print(arr[1:6:2])

[2 4 6]


In [35]:
#6. Reshape a 1D array of size 9 into a 3×3 matrix.

arr = np.array ([1,2,3,4,5,6,7,8,9])
print(arr.shape)

(9,)


In [36]:
ar1 = arr.reshape((3,3))
print(ar1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
