In [2]:
#using python list 
import numpy as np 
import time

size = 1_000_000
l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1,l2)]
end = time.time()

print(end - start)


0.11560630798339844


In [18]:
#using numpy array
import numpy as np 
import time

size = 1_000_000
#making numpy array using list
list1 = np.array(list(range(size)))
list2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2
end = time.time()

print(end - start)

0.0054628849029541016


In [12]:
#now chech memory it takes, so import "sys" module
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
print(f"python list takes: {(sys.getsizeof(list_data)*len(list_data))} bytes")
print(f"numpy array takes: {numpy_data.nbytes} bytes")



python list takes: 8056000 bytes
numpy array takes: 8000 bytes


In [13]:
start = time.time()
list_squares = [x ** 2 for x in l1]
end = time.time()
print(end - start)
 


0.2475571632385254


In [16]:
# NumPy (vectorized)
start = time.time()
numpy_squares = list1 ** 2
end = time.time()
print(end - start)


0.0040929317474365234


In [14]:
# 2D Arrays:

import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(np.sum(arr, axis =0)) # Sum along rows (down each column), Axis 0 = rows (vertical movement)

[12 15 18]


In [9]:
print(np.sum(arr, axis =1)) # Sum along columns (across each row),  Axis 1 = columns (horizontal movement)

[ 6 15 24]


In [13]:
# Indexing in 3D Arrays: For 3D arrays, the first index refers to the “depth” (sheets of data).

arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D)
print(arr3D.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [11]:
# First sheet, second row, third column
print(arr3D[0, 1, 2])

6


In [12]:
print(arr3D[:, 0, :]) # Get the first row from both sheets

[[1 2 3]
 [7 8 9]]


In [30]:
#Why Loops Are Slow:
#squaring in list: This works, but it’s not efficient. Each loop iteration is slow, especially with large datasets.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
start = time.time()
result = []
# Using a loop to square each element (slow)
for num in arr:
    result.append(num ** 2)
end = time.time() 
print(result, end-start)

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)] 0.0003383159637451172


In [31]:
##Vectorization: Fixing the Loop Problem:

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
start = time.time()
result = arr ** 2 # Vectorized operation
end = time.time()
print(result, end-start)

[ 1  4  9 16 25] 0.00029730796813964844


In [32]:
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10 # Broadcasting: 10 is added to all elements
print(result) 

[11 12 13 14 15]
